### ISSUE TITLE
SonarQube login gets redirected back to the login page after entering the admin username and password

### ISSUE THREAD

**Issue by nithinvithayathil** [SonarSource/helm-chart-sonarqube#186]
I am trying to install Sonarqube using helm from repo : [helm-chart-sonarqube/charts/sonarqube at master · SonarSource/helm-chart-sonarqube · GitHub](https://github.com/SonarSource/helm-chart-sonarqube/tree/master/charts/sonarqube)

In values.yaml, i have given the below values;

deploymentType: “Deployment”
replicaCount: 2

ingress:
enabled: true
hosts:
- name:
path: /sonarqube
serviceName: sonarqube-sonarqube
servicePort: 9000 Exact|Prefix|ImplementationSpecific(default)
pathType: Prefix
annotations:
[kubernetes.io/ingress.class:](http://kubernetes.io/ingress.class:) traefik

readinessProbe:
initialDelaySeconds: 60
periodSeconds: 30
failureThreshold: 6
sonarWebContext: /sonarqube/

livenessProbe:
initialDelaySeconds: 60
periodSeconds: 30
failureThreshold: 6
sonarWebContext: /sonarqube/
sonar.web.context: /sonarqube

startupProbe:
initialDelaySeconds: 30
periodSeconds: 10
failureThreshold: 24
sonarWebContext: /sonarqube/

With these configuration, i tried deploying sonar. But i was getting readiness probe failure. So i had given the ingress path which in my case is /sonarqube as an environment variable in deployment file as below,

env:
- name: SONAR_WEB_CONTEXT
value: /sonarqube

After this, the pods are running and i am able to see the login page, But after entering the admin username and password(username: admin, password: admin), it is again getting redirected to the login page. Its not getting logged in.
If i give a wrong password, then i get the authentication error message.

Is there anything, i am doing wrong?

**Comment by tobias-trabelsi-sonarsource** [comment]
Hi @nithinvithayathil ,

please don't ping people with the creation of a GH issue and also please format your `values.yaml` correctly using markdown. It is really hard to read if the scoping is completely missing.

i think your issue is with the `replicaCount: 2`. SQ only supports horizontal scaling with the datacenter edition. All other editions need to stick to 1 replica or you risk loosing sessions or even worse, database corruption. I suggest that you remove your current deployment as well as deleting the PV for the postgresql container that was created and start over with 1 replica

**Comment by nithinvithayathil** [comment]
Thank you Tobias. Changing back the replicaCount to 1 worked. I also had to add the below to environment variable

name: sonar.web.context
value: /sonarqube
