### ISSUE TITLE
new release

### ISSUE THREAD

**Issue by czerasz** [SonarSource/helm-chart-sonarqube#29]
I know asking here might not be the best place...

Could You release the current `master`?
If not now, are there any plans to release soon?

**Comment by k3rnelpan1c-dev** [comment]
Hi czeras,

since this Chart currently isn't hosted on any Helm repository (see #11) I would argue a 'release' would be obsolete for now  (IMHO, and I am not part of SonarSource).
However, you can always clone this repository and install the chart directly form your clone or package and deploy it to an internally hosted Helm repo and use it that way (have tried and done both).

Hope this helps :wink:

**Comment by czerasz** [comment]
@k3rnelpan1c-dev regarding using this repository with Helm I replied in Your issue: https://github.com/SonarSource/helm-chart-sonarqube/issues/11#issuecomment-854158327.

> However, you can always clone this repository and install the chart directly form your clone or package and deploy it to an internally hosted Helm repo and use it that way (have tried and done both).

Cloning/forking is an option but it's counterproductive IMHO since I have to "maintain" by myself. I would prefer (I think this applies to others as well) to use upstream (this repository).

If releasing is not possible I will accept the reality :slightly_smiling_face:

**Comment by k3rnelpan1c-dev** [comment]
Oh dont get me wrong, I too would take a SonarSource Helm repo over cloning this and maintaining the packaged chart in the local helm repo myself any day!
So I totally agree with you.

**Comment by tobias-trabelsi-sonarsource** [comment]
Hi @czerasz 

master has been released yesterday. including pushing the chart to a helm repo. i will write additional more detailed documentation soon :tm: , but in the mean time you can `helm repo add sonarqube https://sonarsource.github.io/helm-chart-sonarqube` and use the charts there
