### ISSUE TITLE
Support for external Elasticsearch instances

### ISSUE THREAD

**Issue by joschi** [SonarSource/helm-chart-sonarqube#67]
As an operator of SonarQube in a Kubernetes cluster, I want to use an external (managed) Elasticsearch cluster instead of spinning up an Elasticsearch node in the SonarQube pod, so that I don't have to care about state in the SonarQube pod.

It's already possible to use an external PostgreSQL service via `postgresql.enabled`, `postgresql.postgresqlServer`, etc. and the environment variable `SONAR_JDBC_URL` respectively (https://docs.sonarqube.org/latest/setup/environment-variables/#header-1).

SonarQube supports providing the URL to an external Elasticsearch cluster via the environment variables `SONAR_SEARCH_HOST` and `SONAR_SEARCH_PORT` (https://docs.sonarqube.org/latest/setup/environment-variables/#header-6).
It doesn't say whether SonarQube supported proper authentication against the Elasticsearch cluster, though.

**Comment by tobias-trabelsi-sonarsource** [comment]
Hi @joschi 

this is a feature request to sonarqube in general and put of scope for this helm chart please create a new post [here](https://community.sonarsource.com/c/suggestions/12). if there is support for that in sonarqube, you can use the [env part](https://github.com/SonarSource/helm-chart-sonarqube/blob/master/charts/sonarqube/values.yaml#L250) in the `values.yaml` to connect your instance to whatever you like

**Comment by joschi** [comment]
@tobias-trabelsi-sonarsource Thanks for your response. 

> this is a feature request to sonarqube in general and put of scope for this helm chart

I respectfully disagree.

There's currently no way to tell this Helm chart to disable the local Elasticsearch node (similar to `postgresql.enabled`), so even when setting the `SONAR_SEARCH_*` environment variables, it will still start and depend on the local Elasticsearch node.

**Comment by tobias-trabelsi-sonarsource** [comment]
yep and this is done in the application. there is currently no way of configuring ES to not start up with SQ on these editions. not much in the helm chart what we can do about that

**Comment by joschi** [comment]
@tobias-trabelsi-sonarsource Fair enough. I see that there have been already a bunch of topics for this request in the forums, e. g. https://community.sonarsource.com/t/34346 and https://community.sonarsource.com/t/11576, which have been closed.

Is this a feature in SonarQube that you're interested in implementing at all?

**Comment by tobias-trabelsi-sonarsource** [comment]
if i understand your point correctly, i would at least create a feature request so that a PM can take a look at it and can evaluate the traction on this topic. the more people request or ask for something the higher the probability that it will be implemented in the end. The linked topics are opened in the "get help" category and one of them is more about separation than externalization. you should definitely reference them in your post as they are related to your concern as well :+1:  

of cause i can not promise you anything but i personally think it's worth a shot as the container world is different from the on prem metal world where you want to have something like ES bundled in order to reduce the complexity of a setup.

**Comment by joschi** [comment]
For reference: I've opened https://community.sonarsource.com/t/support-external-elasticsearch-cluster/47770.
